package com.lxyer.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActLog<M extends BaseActLog<M>> extends Model<M> implements IBean,IModel<M> {

	public void setLogid(java.lang.Integer logid) {
		set("logid", logid);
	}
	
	public java.lang.Integer getLogid() {
		return getInt("logid");
	}

	public void setCate(java.lang.Integer cate) {
		set("cate", cate);
	}
	
	public java.lang.Integer getCate() {
		return getInt("cate");
	}

	public void setTid(java.lang.Integer tid) {
		set("tid", tid);
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}
	
	public java.lang.Long getCreateTime() {
		return getLong("createTime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
