package com.lxyer.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContentItem<M extends BaseContentItem<M>> extends Model<M> implements IBean {

	public void setItemId(java.lang.Integer itemId) {
		set("itemId", itemId);
	}
	
	public java.lang.Integer getItemId() {
		return getInt("itemId");
	}

	public void setContentId(java.lang.Integer contentId) {
		set("contentId", contentId);
	}
	
	public java.lang.Integer getContentId() {
		return getInt("contentId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
