package com.lxyer.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setCommentId(java.lang.Integer commentId) {
		set("commentId", commentId);
	}
	
	public java.lang.Integer getCommentId() {
		return getInt("commentId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public void setCate(java.lang.Integer cate) {
		set("cate", cate);
	}
	
	public java.lang.Integer getCate() {
		return getInt("cate");
	}

	public void setContentId(java.lang.Integer contentId) {
		set("contentId", contentId);
	}
	
	public java.lang.Integer getContentId() {
		return getInt("contentId");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}
	
	public java.lang.Long getCreateTime() {
		return getLong("createTime");
	}

	public void setSupportNum(java.lang.Integer supportNum) {
		set("supportNum", supportNum);
	}
	
	public java.lang.Integer getSupportNum() {
		return getInt("supportNum");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
