package com.lxyer.model;

import com.lxyer.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment().dao();

	@Override
	public String sqlSpace() {
		return "comment";
	}

	@Override
	public Comment getDao() {
		return dao;
	}
}
