package com.lxyer.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Db;
import com.lxyer.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment().dao();

	@Override
	public String sqlSpace() {
		return "comment";
	}

	@Override
	public Comment getDao() {
		return dao;
	}

	/**
	 * 更新点赞数
	 * @param commentId
	 */
	public static void upSupportNum(Integer commentId) {
		Db.update(Db.getSqlPara("comment.upSupportNum", Kv.by("commentId", commentId)));
	}
}
