package com.lxyer.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Db;
import com.lxyer.model.base.BaseContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
    public static final Content dao = new Content().dao();

    @Override
    public String sqlSpace() {
        return "content";
    }

    @Override
    public Content getDao() {
        return dao;
    }

    public static void upReplyNum(int contentId){
        Db.update(Db.getSqlPara("content.upReplyNum", Kv.by("contentId", contentId)));
    }
}
