package com.lxyer.model;

import com.lxyer.model.base.BaseContentItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentItem extends BaseContentItem<ContentItem> {
	
}
