package com.lxyer.model;

import com.lxyer.model.base.BaseContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
    public static final Content dao = new Content().dao();

    @Override
    public String sqlSpace() {
        return "content";
    }
}
