package com.lxyer.model;

import com.lxyer.config.LxyKit;
import com.lxyer.model.base.BaseUserPwd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPwd extends BaseUserPwd<UserPwd> {
    public static final UserPwd dao = new UserPwd().dao();

    @Override
    public boolean save() {
        setUpdateTime(System.currentTimeMillis());
        setPwd(LxyKit.md5IfNeed(getPwd()));
        if (findById(getUserId()) == null) {
            return super.save();
        }else {
            return super.update();
        }
    }

    @Override
    public boolean update() {
        return save();
    }
}
